name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
   
jobs:
  predeploy:
    runs-on: ubuntu-20.04
    env:
      MONGO_URI: ${{  secrets.MONGO_URI }}
      TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Test UI
        run: npm run test:ui
      - name: Build UI
        run: npm run build:ui
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:8080

  deploy:
    needs: [predeploy]
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
      - name: Install deps
        run: npm ci
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm run build:ui && flyctl deploy --remote-only